[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/usr/local/bin/start.sh"
healthcheckPath = "/health.php"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
# Railway會自動設置這些環境變數
# DB_HOST - MySQL服務的主機名
# DB_USER - 資料庫用戶名
# DB_PASSWORD - 資料庫密碼
# DB_NAME - 資料庫名稱
# PORT - 應用端口
